apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-multicluster
  namespace: argocd
spec:
  generators:
    - merge:
        mergeKeys:
          - path.basename
        generators:
          - list:
              elements:
                - component: istio-base
                  wave: "0"
                - component: istiod
                  wave: "1"
                - component: gateway
                  wave: "2"
          - git:
              repoURL: https://github.com/your-org/gitops-istio-multicluster
              revision: HEAD
              directories:
                - path: clusters/*
  template:
    metadata:
      name: '{{path.basename}}-{{component}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: '{{component}}'
        targetRevision: 1.23.0
        helm:
          valueFiles:
            - clusters/{{path.basename}}/istio-{{component}}-values.yaml
      destination:
        name: '{{path.basename}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
