# global:
#   istioNamespace: istio-system

# gateways:
#   istio-ingressgateway:
#     autoscaleEnabled: true
#     type: LoadBalancer
#     labels:
#       app: istio-ingressgateway
#     ports:
#       - name: status-port
#         port: 15021
#         targetPort: 15021
#       - name: http2
#         port: 80
#         targetPort: 8080
#       - name: https
#         port: 443
#         targetPort: 8443
#     resources:
#       requests:
#         cpu: 500m
#         memory: 512Mi
#       limits:
#         cpu: 1000m
#         memory: 1Gi
